version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: edbo-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      # local->container
      - $NODE_PORT:$NODE_PORT
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - TZ=Europe/Kiev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: edbo-client
    stdin_open: true
    tty: true
    ports:
      # local->container
      - '5173:5173'
    volumes:
      - ./client:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Europe/Kiev
    depends_on:
      - api

  postgres:
    image: postgres
    container_name: edbo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  postgres_data:
