version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: edbo-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      # local->container
      - $NODE_PORT:$NODE_PORT
    volumes:
      - ./api:/app
      - /api/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: edbo-client
    stdin_open: true
    tty: true
    ports:
      # local->container
      - '5173:5173'
    volumes:
      - ./client:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  mongodb:
    image: mongo
    container_name: edbo-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
